### ISSUE TITLE
Add-on: Front-end

### ISSUE THREAD

**Issue by a0xz** [w1ld3r/Rotulus#10]
You can developer the front in Python, Elixir or Golang

**Comment by w1ld3r** [comment]
I was thinking in React ...

**Comment by a0xz** [comment]
Ok, good.
If you can help, contact me.

**Comment by w1ld3r** [comment]
Are you a typescript developer ?

**Comment by a0xz** [comment]
Yes!

**Comment by w1ld3r** [comment]
Would you be interested by developing the frontend ?

**Comment by a0xz** [comment]
Yes!
