### ISSUE TITLE
Suggestion: Support email:username:password

### ISSUE THREAD

**Issue by uBadRequest** [w1ld3r/Rotulus#3]
There will be cases where data comes in that comes with an email address and a username. Being able to insert both would be ideal for doing searches where you can match an email address and find a username, that then matches to other passwords.

**Comment by w1ld3r** [comment]
Hello @uBadRequest , the code has been re developped and allow you more flexibility !

**Comment by w1ld3r** [comment]
Hope it will resolve you issue.
